#!/bin/bash
# arch-install - minimal Arch Linux installer based on arch-install-scripts
# assumes you have created partitions, filesystems & are they are mounted to new_arch
#
# by Mr Green
#

# Checks might be a better way to test!
if [[ $(pacman -Qq arch-install-scripts) != arch-install-scripts ]]; then
	echo "arch-install-scripts not installed" && exit
fi

if [ $EUID != 0 ] ; then
  echo "Need to run as root.  Terminating..." >&2
  exit 1
fi

new_arch=/mnt
ACM="arch-chroot ${new_arch}"
new_etc="${new_arch}/etc"

# Username and passwords
wired=true
user_groups="adm,storage,optical,audio,video,network,wheel,power,lp,log"
user_name="archuser"
user_passwd="password"
root_passwd="password"

# System settings
host_name="archlinux"
keymap="KEYMAP=uk"
locale="en_GB.UTF-8"
time_zone="Europe/London"

# Install base syslinux and packages in package_list
pacstrap ${new_arch} base syslinux $(<package_list) 

# Create fstab
genfstab -p -U ${new_arch} >> ${new_etc}/fstab

# Timezone
ln -s ${new_arch}/usr/share/zoneinfo/${time_zone} ${new_etc}/localtime

# Hostname
echo ${host_name} > ${new_etc}/hostname

# Locale and keymap
echo ${keymap} > ${new_etc}/vconsole.conf
echo "LANG=${locale}" > ${new_etc}/locale.conf
echo "${locale} UTF-8" > ${new_etc}/locale.gen

# Add user and set up passwords
$ACM useradd -m -g users -G ${user_groups} -s /bin/bash ${user_name}
echo "${user_name}:${user_password}" | $ACM chpasswd
echo "root:${root_passwd}" | $ACM chpasswd

# Install kernel
$ACM mkinitcpio -p linux
$ACM locale-gen

# Enable wired network
[[ ${wired} == true ]] && $ACM /usr/bin/systemctl -f enable dhcpcd.service

# Bootloader
root_part=$(df | grep -w ${new_arch} | awk {'print $1'})
sed -i "s|/dev/sda3|$root_part|g" ${new_arch}/boot/syslinux/syslinux.cfg
$ACM syslinux-install_update -iam

# Setup Openbox 
echo "exec openbox-session" >> ${new_arch}/home/$user_name}/.xinitrc
mkdir -p {new_arch}/home/${user_name}/.config/openbox
cp ${new_arch}/etc/xdg/openbox/{rc.xml,menu.xml,autostart,environment} \
	 ${new_arch}/home/${user_name}/.config/openbox
# check ownership of files...
