#!/bin/bash
# arch-install - Arch Linux installer using arch-install-scripts
# assumes you have created partitions, filesystems & are they are mounted to new_arch
#
# by Mr Green
#
script_path=$(readlink -f ${0%/*})

if [ ! -f /usr/bin/pacstrap ]; then
	echo "arch-install-scripts not installed" && exit
fi

if [ $EUID != 0 ] ; then
  echo "Please run as root.  Terminating..." >&2
  exit 1
fi

# Target directories
new_arch=/mnt
[ ! -d ${new_arch} ] && mkdir -p ${new_arch}
ACM="arch-chroot ${new_arch}"
new_etc="${new_arch}/etc"

# Username and passwords
wired=true
aur=true
user_groups="adm,storage,optical,audio,video,network,wheel,power,lp,log"
user_name="archuser"
user_passwd="password"
root_passwd="password"

# System settings
host_name="archlinux"
keymap="KEYMAP=uk"
locale="en_GB.UTF-8"
time_zone="Europe/London"

install_packer()
{
pacstrap ${new_arch} base-devel curl git
$ACM << EOF
curl -O https://aur.archlinux.org/packages/pa/packer/packer.tar.gz
tar -zxvf packer.tar.gz
rm packer.tar.gz
cd packer
makepkg -is --noconfirm --asroot
EOF 
}


# Install base syslinux and packages in package_list
pacstrap ${new_arch} base syslinux $(grep -v "^#" ${script_path}/package_list)

# Install packer is aur true
[[ ${aur} == true ]] && install_packer

# Create fstab
genfstab -p -U ${new_arch} >> ${new_etc}/fstab

# Timezone
ln -s ${new_arch}/usr/share/zoneinfo/${time_zone} ${new_etc}/localtime

# Hostname
echo ${host_name} > ${new_etc}/hostname

# Locale and keymap
echo ${keymap} > ${new_etc}/vconsole.conf
echo "LANG=${locale}" > ${new_etc}/locale.conf
echo "${locale} UTF-8" > ${new_etc}/locale.gen

# Install kernel
$ACM mkinitcpio -p linux
$ACM locale-gen

# Enable wired network
[[ ${wired} == true ]] && $ACM /usr/bin/systemctl -f enable dhcpcd.service

# Bootloader
root_part=$(df | grep -w ${new_arch} | awk {'print $1'})
sed -i "s|/dev/sda3|$root_part|g" ${new_arch}/boot/syslinux/syslinux.cfg
$ACM syslinux-install_update -iam

# Setup Openbox
mkdir -p ${new_arch}/etc/skel/.config/openbox
echo "exec openbox-session" >> ${new_arch}/etc/skel/.xinitrc
cp ${new_arch}/etc/xdg/openbox/{rc.xml,menu.xml,autostart,environment} \
	 ${new_arch}/etc/skel/.config/openbox

# Add user and set up passwords
$ACM useradd -m -g users -G ${user_groups} -s /bin/bash ${user_name}
echo "${user_name}:${user_passwd}" | $ACM chpasswd
echo "root:${root_passwd}" | $ACM chpasswd

# Remove /etc/skel from ${new_arch}
# rm -rf ${new_arch}/etc/skel/
# rmdir ${new_arch}/etc/skel

